display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-tmc-common
telescope: SKA-mid

labels:
  app: ska-tmc-common

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.13
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.5.0
    pullPolicy: IfNotPresent


test_device:
  image:
    registry: artefact.skao.int
    image: ska-tmc-common
    tag: 0.22.0
    pullPolicy: IfNotPresent

deviceServers:
  mocks:
    enabled: true
    file: "data/mock.yaml"

nodeSelector: {}

affinity: {}

tolerations: []
