# -*- coding: utf-8 -*-
#
# This file is part of the SampleServer project
#
#
#
# Distributed under the terms of the GPL license.
# See LICENSE.txt for more info.

""" SampleDevice

Code for Tango interface layer sample.
"""

# PyTango imports
import PyTango
from PyTango import DebugIt
from PyTango.server import run
from PyTango.server import Device, DeviceMeta
from PyTango.server import attribute, command
from PyTango import AttrWriteType
# Additional import
from tmc.common.tango_server_helper import TangoServerHelper

__all__ = ["SampleDevice", "main", "TestCommand"]


class SampleDevice(Device):
    """
    This is the sample Tango device class.
    """
    __metaclass__ = DeviceMeta
       
    def always_executed_hook(self):
        pass

    def delete_device(self):
        pass

    def read_testattr(self):
        """
        Default attribute read method generated by POGO.
        """
        return self._testattr

    def write_testattr(self, value):
        """
        Default attribute write method generated by POGO.
        """
        self._testattr = testattr

    def init_device(self):
        Device.init_device(self)
        self._testattr = 0
        self.set_state()


def main(args=None, **kwargs):

    return run((SampleDevice,), args=args, **kwargs)


if __name__ == '__main__':
    main()

# --------
# Commands
# --------

@command(
    dtype_in='str',
    )

class TestCommand(self):
    """
    Code for TestCommand command execution .
    """

    #Returns instance object of TangoServerHelper class. 
    #Creates one if the object does not exist.
    sample_server = TangoServerHelper.get_instance()

    def do():

        #Returns the value of given device property in string type
        sample_server.get_property(test_property)

        #Sets the value to a given device property
        sample_server.set_property(test_property, "sys/tg_test/1")

        #Returns value of the status attribute of the Tango device.
        sample_server.get_status()

        #Sets the status attribute of the Tango device with given value.
        sample_server.set_status("test_attr is ON")

        #Returns value of the state attribute of the Tango device.
        sample_server.get_state()

        #Sets the state attribute of the Tango device with given value.
        sample_server.set_state(DevState.ON)
