"""Constants
"""

ON = "On"
OFF = "Off"
STAND_BY = "Standby"
ASSIGN_RESOURCES = "AssignResources"
CONFIGURE = "Configure"
CONFIGURE_BAND_2 = "ConfigureBand2"
CONFIGURE_BAND_1 = "ConfigureBand1"
RELEASE_RESOURCES = "ReleaseResources"
ABORT = "Abort"
APPLY_POINT_MODEL = "ApplyPointingModel"
RESTART = "Restart"
RESTARTSUBARRAY = "RestartSubarray"
END = "End"
OBS_RESET = "ObsReset"
SCAN = "Scan"
END_SCAN = "EndScan"
RELEASE_ALL_RESOURCES = "ReleaseAllResources"
GO_TO_IDLE = "GoToIdle"
SLEW = "Slew"
RESET = "Reset"

ALLOCATE = "Allocate"
RELEASE = "Release"

TRACK = "Track"
TRACK_STOP = "TrackStop"
ABORT_COMMANDS = "AbortCommands"
SET_STANDBY_FP_MODE = "SetStandbyFPMode"
SET_STANDBY_LP_MODE = "SetStandbyLPMode"
SET_STOW_MODE = "SetStowMode"
SET_OPERATE_MODE = "SetOperateMode"
SKA_EPOCH = "1999-12-31T23:59:28Z"
